### PR TITLE
Simple CLI for creating SIPs  and Security Fixes

### LINKED ISSUE #98: Remove spring-core as a dependency of the PyIP compatible report

### LINKED ISSUE #103: Simple CLI for creating SIPs
- [x] Allow to select descriptive metadata file(s)
- [x] Allow to select a set of files as representation data
- [x] Allow to define a set of ancestor IDs

Additional parameters for required information.

### PR DESCRIPTION
**Pull request by JoaoGomes2110**
- fix #103 
- fix #98

### CODE REVIEW

File: src/main/java/org/roda_project/commons_ip2/validator/CLI/CLIConstants.java [hunk 1]
```diff
@@ -1,14 +1,275 @@
...
+   */
+  public static final String CLI_CREATE_OPTION_REPRESENTATION_ID = "-rid";
+
+  /**
+   * CLI option to choose the representation type.
+   */
+  public static final String CLI_CREATE_OPTION_REPRESENTATION_TYPE = "-rt";
+
+  /**
+   * CLI option to add ancestprs to the SIP.
```
Comment (hmiguim) [inline src/main/java/org/roda_project/commons_ip2/validator/CLI/CLIConstants.java:74]: typo: ancestors

File: src/main/java/org/roda_project/commons_ip2/validator/CLI/CLIConstants.java [hunk 2]
```diff
@@ -1,14 +1,275 @@
...
+
+  /**
+   * CLI option to give the path to save the SIP.
+   */
+  public static final String CLI_CREATE_OPTION_PATH = "-p";
+
+  /**
+   * CLI option to give the submitter agent name.
+   */
+  public static final String CLI_CREATE_OPTION_SUBMITTER_AGENT_NAME = "-sn";
```
Comment (hmiguim) [inline src/main/java/org/roda_project/commons_ip2/validator/CLI/CLIConstants.java:96]: maybe it is better: -san

**Review by hmiguim — CHANGES_REQUESTED** [review]
