### PR TITLE
Fixed #165

### LINKED ISSUE #165: CSIP88 validation fails despite correctly labeled metadata div
With descriptive metadata being present and referenced, and a `mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Metadata']` present like required by CSIP88 validation fails with

```json
{
    "specification" : "CSIP-2.0.4",
    "id" : "CSIP88",
    "name" : "Metadata division",
    "location" : "mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Metadata']",
    "description" : "The metadata referenced in the administrative and/or descriptive metadata section is described in the structural map with one sub division.When the transfer consists of only administrative and/or descriptive metadata this is the only sub division that occurs.",
    "cardinality" : "1..1",
    "level" : "MUST",
    "testing" : {
      "outcome" : "FAILED",
      "issues" : [ "You have metadata files, must add mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Metadata'] in Root METS.xml" ],
      "warnings" : [ ],
      "notes" : [ ]
    }
}
```

I see there was a related issue #54 which [changed](https://github.com/keeps/commons-ip/commit/52b99fe7ca91f08128b9311f7cb4a1afc2f8eb4b#diff-869153069bd2d62c4cd5e6b54a8da4c7a6480818828280632369cc5600c39f14L626) the related logic to fail when the div with the required label is found?

### PR DESCRIPTION
**Pull request by carlosjepard**

### CODE REVIEW

File: src/main/java/org/roda_project/commons_ip2/validator/component/structuralMapComponent/StructuralMapComponentValidator.java [hunk 1]
```diff
@@ -673,15 +673,27 @@ private ReporterDetails validateCSIP88(final MetsValidatorState metsValidatorSta
         final DivType div = struct.getDiv();
         if (div != null && div.getLABEL().equals("CSIP")) {
```
Comment (prettybits) [inline src/main/java/org/roda_project/commons_ip2/validator/component/structuralMapComponent/StructuralMapComponentValidator.java:674]: Instead of checking the division for the label here the current `struct`(Map) needs to be checked whether it has a label and if it is "CSIP" above.

**Review by hmiguim — APPROVED** [review]
